-- ============================================================
-- Table: asset
-- Rows:  50
-- Generated: 2026-09-10T22:09:57.256399
-- ============================================================

-- Clear existing data
DELETE FROM asset;

-- 50 rows
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-C2101', 'C-2101', 'Hydrocracker recycle gas compressor', 'Z2', 'Centrifugal compressor', 'high', 62, 'degraded', 'alarm', 'Vibration high — stage 2 bearing', 'worsening', 'Overall vibration up 41% in 14 days; the step change lines up with the Feb turnaround restart.', 21, 'days', 71, 'Vibration trend extrapolated to the 7.1 mm/s trip threshold.', '2026-08-19', 'Planned bearing inspection', 'Turnaround window T-3', 'Six of the 88 open permits on Unit 2 are within the compressor''s exclusion radius, two of them hot work.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE1602', 'CE-1602', 'Centrifugal pump — Unit 4', 'Z4', 'Centrifugal pump', 'high', 86, 'watch', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-25', 'Calibration', 'T-1', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE2029', 'CE-2029', 'Centrifugal compressor — Control', 'Z8', 'Centrifugal compressor', 'high', 80, 'watch', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-14', 'Bearing replacement', 'T-4', 'Asset condition may affect nearby permits in Control.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE3065', 'CE-3065', 'Centrifugal compressor — Unit 3', 'Z3', 'Centrifugal compressor', 'high', 96, 'healthy', 'attention', 'Centrifugal compressor alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-02', 'Bearing replacement', 'T-2', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE4909', 'CE-4909', 'Centrifugal compressor — Unit 5', 'Z5', 'Centrifugal compressor', 'low', 50, 'critical', 'attention', 'Centrifugal compressor alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 184, 'days', 89, 'Trend extrapolation', '2026-08-27', 'Bearing replacement', 'T-4', 'Asset condition may affect nearby permits in Unit 5.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE6057', 'CE-6057', 'Centrifugal pump — Workshop', 'Z9', 'Centrifugal pump', 'medium', 96, 'healthy', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-18', 'Calibration', 'T-4', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE6318', 'CE-6318', 'Centrifugal compressor — Unit 2', 'Z2', 'Centrifugal compressor', 'low', 81, 'watch', 'attention', 'Centrifugal compressor alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-16', 'Calibration', 'T-5', 'Asset condition may affect nearby permits in Unit 2.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE8649', 'CE-8649', 'Centrifugal pump — Admin', 'Z10', 'Centrifugal pump', 'high', 92, 'healthy', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-03', 'Bearing replacement', 'T-5', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE9260', 'CE-9260', 'Centrifugal pump — Gate', 'Z11', 'Centrifugal pump', 'medium', 93, 'healthy', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-18', 'Seal inspection', 'T-5', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CE9879', 'CE-9879', 'Centrifugal compressor — Unit 6', 'Z6', 'Centrifugal compressor', 'high', 90, 'healthy', 'alarm', 'Centrifugal compressor alarm condition', 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-02', 'Bearing replacement', 'T-3', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-CO9536', 'CO-9536', 'Control valve — Gate', 'Z11', 'Control valve', 'low', 86, 'watch', 'attention', 'Control valve alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-31', 'Seal inspection', 'T-2', 'Asset condition may affect nearby permits in Gate.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA1683', 'GA-1683', 'Gas detector — Admin', 'Z10', 'Gas detector', 'high', 88, 'watch', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-11', 'Bearing replacement', 'T-5', 'Asset condition may affect nearby permits in Admin.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA1811', 'GA-1811', 'Gas detector — Unit 1', 'Z1', 'Gas detector', 'high', 93, 'healthy', 'alarm', 'Gas detector alarm condition', 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-29', 'Seal inspection', 'T-3', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA1967', 'GA-1967', 'Gas detector — Control', 'Z8', 'Gas detector', 'low', 64, 'degraded', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 20, 'days', 61, 'Trend extrapolation', '2026-09-11', 'Calibration', 'T-3', 'Asset condition may affect nearby permits in Control.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA2495', 'GA-2495', 'Gas detector — Unit 1', 'Z1', 'Gas detector', 'medium', 55, 'critical', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', 355, 'days', 71, 'Trend extrapolation', '2026-08-20', 'Routine inspection', 'T-3', 'Asset condition may affect nearby permits in Unit 1.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA5380', 'GA-5380', 'Gas detector — Unit 2', 'Z2', 'Gas detector', 'high', 94, 'healthy', 'alarm', 'Gas detector alarm condition', 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-10', 'Calibration', 'T-5', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA7853', 'GA-7853', 'Gas detector — Unit 6', 'Z6', 'Gas detector', 'medium', 87, 'watch', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-22', 'Routine inspection', 'T-2', 'Asset condition may affect nearby permits in Unit 6.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GA8816', 'GA-8816', 'Gas detector — Unit 4', 'Z4', 'Gas detector', 'low', 85, 'watch', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-12', 'Calibration', 'T-4', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-GD3307', 'GD-3307', 'Fixed gas detector — Unit 3 south manifold', 'Z3', 'Gas detector', 'high', 78, 'watch', 'attention', 'Calibration due in 2 days', 'stable', 'Calibration interval approaching; unit still within tolerance.', 2, 'days', 90, 'Days since last calibration vs 90-day interval.', '2026-08-07', 'Gas detector calibration', 'Routine maintenance slot', 'Detector covers the south manifold area where CS-1182 is active.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE2797', 'HE-2797', 'Heat exchanger — Unit 6', 'Z6', 'Heat exchanger', 'high', 51, 'critical', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 321, 'days', 66, 'Trend extrapolation', '2026-10-27', 'Seal inspection', 'T-1', 'Asset condition may affect nearby permits in Unit 6.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE3143', 'HE-3143', 'Heat exchanger — Gate', 'Z11', 'Heat exchanger', 'low', 91, 'healthy', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-28', 'Calibration', 'T-4', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE3866', 'HE-3866', 'Heat exchanger — Unit 5', 'Z5', 'Heat exchanger', 'high', 74, 'degraded', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 233, 'days', 88, 'Trend extrapolation', '2026-08-28', 'Routine inspection', 'T-3', 'Asset condition may affect nearby permits in Unit 5.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE4222', 'HE-4222', 'Heat exchanger — Control', 'Z8', 'Heat exchanger', 'medium', 73, 'degraded', 'attention', 'Heat exchanger alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 197, 'days', 70, 'Trend extrapolation', '2026-08-25', 'Seal inspection', 'T-3', 'Asset condition may affect nearby permits in Control.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE6852', 'HE-6852', 'Heat exchanger — Unit 1', 'Z1', 'Heat exchanger', 'low', 58, 'critical', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', 193, 'days', 70, 'Trend extrapolation', '2026-10-20', 'Seal inspection', 'T-3', 'Asset condition may affect nearby permits in Unit 1.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-HE9107', 'HE-9107', 'Heat exchanger — Unit 6', 'Z6', 'Heat exchanger', 'low', 81, 'watch', 'attention', 'Heat exchanger alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-04', 'Routine inspection', 'T-4', 'Asset condition may affect nearby permits in Unit 6.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-P1044', 'P-1044', 'Crude charge pump', 'Z1', 'Centrifugal pump', 'medium', 91, 'healthy', NULL, NULL, 'stable', 'All readings within normal operating range.', NULL, NULL, NULL, NULL, '2026-09-15', 'Routine seal inspection', 'T-4', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR2677', 'PR-2677', 'Pressure vessel — Unit 3', 'Z3', 'Pressure vessel', 'low', 100, 'healthy', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-01', 'Calibration', 'T-2', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR2721', 'PR-2721', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'low', 80, 'watch', 'attention', 'Pressure vessel alarm condition', 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-26', 'Calibration', 'T-3', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR4168', 'PR-4168', 'Pressure vessel — Unit 6', 'Z6', 'Pressure vessel', 'medium', 71, 'degraded', 'attention', 'Pressure vessel alarm condition', 'improving', 'Trend is improving over last 14 days.', 280, 'days', 63, 'Trend extrapolation', '2026-10-23', 'Calibration', 'T-4', 'Asset condition may affect nearby permits in Unit 6.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR4473', 'PR-4473', 'Pressure vessel — Unit 5', 'Z5', 'Pressure vessel', 'low', 93, 'healthy', 'attention', 'Pressure vessel alarm condition', 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-14', 'Routine inspection', 'T-2', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR5770', 'PR-5770', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'medium', 66, 'degraded', 'attention', 'Pressure vessel alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 318, 'days', 91, 'Trend extrapolation', '2026-09-24', 'Calibration', 'T-2', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR6090', 'PR-6090', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'medium', 66, 'degraded', 'attention', 'Pressure vessel alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 30, 'days', 72, 'Trend extrapolation', '2026-09-02', 'Seal inspection', 'T-5', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR6275', 'PR-6275', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'medium', 62, 'degraded', 'attention', 'Pressure vessel alarm condition', 'stable', 'Trend is stable over last 14 days.', 192, 'days', 78, 'Trend extrapolation', '2026-10-05', 'Routine inspection', 'T-1', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR6546', 'PR-6546', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'high', 63, 'degraded', 'attention', 'Pressure vessel alarm condition', 'stable', 'Trend is stable over last 14 days.', 299, 'days', 82, 'Trend extrapolation', '2026-08-28', 'Calibration', 'T-5', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR6725', 'PR-6725', 'Pressure vessel — Unit 2', 'Z2', 'Pressure vessel', 'high', 95, 'healthy', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-05', 'Bearing replacement', 'T-1', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR6766', 'PR-6766', 'Pressure vessel — Unit 4', 'Z4', 'Pressure vessel', 'low', 51, 'critical', 'attention', 'Pressure vessel alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 25, 'days', 82, 'Trend extrapolation', '2026-09-25', 'Seal inspection', 'T-1', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-PR9416', 'PR-9416', 'Pressure vessel — Workshop', 'Z9', 'Pressure vessel', 'low', 98, 'healthy', 'attention', 'Pressure vessel alarm condition', 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-17', 'Bearing replacement', 'T-2', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-RO1470', 'RO-1470', 'Rotating equipment — Unit 5', 'Z5', 'Rotating equipment', 'high', 90, 'healthy', 'alarm', 'Rotating equipment alarm condition', 'improving', 'Trend is improving over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-23', 'Routine inspection', 'T-2', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-RO3254', 'RO-3254', 'Rotating equipment — Admin', 'Z10', 'Rotating equipment', 'high', 74, 'degraded', 'alarm', 'Rotating equipment alarm condition', 'stable', 'Trend is stable over last 14 days.', 20, 'days', 84, 'Trend extrapolation', '2026-08-25', 'Seal inspection', 'T-3', 'Asset condition may affect nearby permits in Admin.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-RO8132', 'RO-8132', 'Rotating equipment — Unit 7', 'Z7', 'Rotating equipment', 'high', 70, 'degraded', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 175, 'days', 88, 'Trend extrapolation', '2026-08-20', 'Seal inspection', 'T-2', 'Asset condition may affect nearby permits in Unit 7.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-RO8415', 'RO-8415', 'Rotating equipment — Control', 'Z8', 'Rotating equipment', 'medium', 77, 'watch', 'attention', 'Rotating equipment alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-08-29', 'Bearing replacement', 'T-2', 'Asset condition may affect nearby permits in Control.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-RO9442', 'RO-9442', 'Rotating equipment — Admin', 'Z10', 'Rotating equipment', 'low', 50, 'critical', NULL, NULL, 'improving', 'Trend is improving over last 14 days.', 245, 'days', 60, 'Trend extrapolation', '2026-09-29', 'Seal inspection', 'T-4', 'Asset condition may affect nearby permits in Admin.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA1701', 'SA-1701', 'Safety relief valve — Admin', 'Z10', 'Safety relief valve', 'medium', 69, 'degraded', 'alarm', 'Safety relief valve alarm condition', 'improving', 'Trend is improving over last 14 days.', 290, 'days', 63, 'Trend extrapolation', '2026-08-31', 'Bearing replacement', 'T-5', 'Asset condition may affect nearby permits in Admin.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA3658', 'SA-3658', 'Safety relief valve — Unit 4', 'Z4', 'Safety relief valve', 'high', 97, 'healthy', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-12', 'Seal inspection', 'T-3', 'No active HSE implications.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA4208', 'SA-4208', 'Safety relief valve — Gate', 'Z11', 'Safety relief valve', 'low', 70, 'degraded', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 84, 'days', 69, 'Trend extrapolation', '2026-10-18', 'Seal inspection', 'T-5', 'Asset condition may affect nearby permits in Gate.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA4291', 'SA-4291', 'Safety relief valve — Gate', 'Z11', 'Safety relief valve', 'medium', 69, 'degraded', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', 149, 'days', 66, 'Trend extrapolation', '2026-09-21', 'Seal inspection', 'T-4', 'Asset condition may affect nearby permits in Gate.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA7934', 'SA-7934', 'Safety relief valve — Admin', 'Z10', 'Safety relief valve', 'medium', 81, 'watch', NULL, NULL, 'stable', 'Trend is stable over last 14 days.', NULL, NULL, NULL, NULL, '2026-10-25', 'Routine inspection', 'T-1', 'Asset condition may affect nearby permits in Admin.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA8446', 'SA-8446', 'Safety relief valve — Unit 3', 'Z3', 'Safety relief valve', 'high', 62, 'degraded', 'alarm', 'Safety relief valve alarm condition', 'worsening', 'Trend is worsening over last 14 days.', 355, 'days', 66, 'Trend extrapolation', '2026-09-17', 'Calibration', 'T-3', 'Asset condition may affect nearby permits in Unit 3.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA8534', 'SA-8534', 'Safety relief valve — Unit 4', 'Z4', 'Safety relief valve', 'medium', 69, 'degraded', NULL, NULL, 'worsening', 'Trend is worsening over last 14 days.', 80, 'days', 74, 'Trend extrapolation', '2026-08-23', 'Bearing replacement', 'T-1', 'Asset condition may affect nearby permits in Unit 4.');
INSERT INTO asset (id, tag, name, zone_id, asset_type, criticality, health_score, health_band, alarm_state, alarm_label, trend, trend_note, rul_value, rul_unit, rul_confidence, rul_basis, next_service_due, next_service_type, next_service_window, hse_implication) VALUES ('AST-SA8538', 'SA-8538', 'Safety relief valve — Admin', 'Z10', 'Safety relief valve', 'low', 81, 'watch', 'attention', 'Safety relief valve alarm condition', 'worsening', 'Trend is worsening over last 14 days.', NULL, NULL, NULL, NULL, '2026-09-19', 'Bearing replacement', 'T-4', 'Asset condition may affect nearby permits in Admin.');